chrome.runtime.onInstalled.addListener(function(details){
    var defaultSettings = {
		censorCharacter: "****",
		filterMethod: "0",
		filterToggle: false,
		matchMethod: "0",
		password: "null", 
		warningDomains: [
			"https://www.facebook.com",
			"https://www.twitter.com",
			"https://www.9gag.com",
			"https://www.tumblr.com",
			"https://www.youtube.com",
		],
		websites: [
			{"count": "3358","site": "https://www.google.com.ph"},
			{"count": "249","site": "https://notifications.google.com"},
			{"count": "143","site": "https://www.youtube.com"},
			{"count": "128","site": "https://www-urbandictionary-com.cdn.ampproject.org"},
			{"count": "118","site": "https://stackoverflow.com"}
			],
		defaultWords: [
			{"count": 0,"word": "fuck"},
			{"count": 0,"word": "fuckable"},
			{"count": 0,"word": "fucked"},
			{"count": 0,"word": "fucker"},
			{"count": 0,"word": "fuckin"},
			{"count": 0,"word": "fucks"},
			{"count": 0,"word": "fvck"},
			{"count": 0,"word": "shit"},
			{"count": 0,"word": "asses"},
			{"count": 0,"word": "asshole"},
			{"count": 0,"word": "assshit"},
			{"count": 0,"word": "ass-hat"},
			{"count": 0,"word": "asssucker"},
			{"count": 0,"word": "assbag"},
			{"count": 0,"word": "assbite"},
			{"count": 0,"word": "asscock"},
			{"count": 0,"word": "assfuck"},
			{"count": 0,"word": "asshead"},
			{"count": 0,"word": "asslick"},
			{"count": 0,"word": "asslicker"},
			{"count": 0,"word": "assmonkey"},
			{"count": 0,"word": "assmunch"},
			{"count": 0,"word": "anal"},
			{"count": 0,"word": "bastard"},
			{"count": 0,"word": "blowjob"},
			{"count": 0,"word": "bampot"},
			{"count": 0,"word": "bitchass"},
			{"count": 0,"word": "bitchy"},
			{"count": 0,"word": "bullshit"},
			{"count": 0,"word": "bitch"},
			{"count": 0,"word": "cunt"},
			{"count": 0,"word": "creampie"},
			{"count": 0,"word": "cum"},
			{"count": 0,"word": "clitface"},
			{"count": 0,"word": "clusterfuck"},
			{"count": 0,"word": "cockass"},
			{"count": 0,"word": "cockbite"},
			{"count": 0,"word": "cockburger"},
			{"count": 0,"word": "cockface"},
			{"count": 0,"word": "cockhead"},
			{"count": 0,"word": "cockmonkey"},
			{"count": 0,"word": "cocknose"},
			{"count": 0,"word": "cocknugget"},
			{"count": 0,"word": "cockshit"},
			{"count": 0,"word": "cockwaffle"},
			{"count": 0,"word": "cumbubble"},
			{"count": 0,"word": "cumslut"},
			{"count": 0,"word": "cumtart"},
			{"count": 0,"word": "cuntass"},
			{"count": 0,"word": "cumdumpster"},
			{"count": 0,"word": "cuntface"},
			{"count": 0,"word": "cuntrag"},
			{"count": 0,"word": "cuntslut"},
			{"count": 0,"word": "cock"},
			{"count": 0,"word": "damn"},
			{"count": 0,"word": "expression"},
			{"count": 0,"word": "douche"},
			{"count": 0,"word": "douchebag"},
			{"count": 0,"word": "insensitive"},
			{"count": 0,"word": "deepthroat"},
			{"count": 0,"word": "dildo"},
			{"count": 0,"word": "dildos"},
			{"count": 0,"word": "dickbag"},
			{"count": 0,"word": "dickface"},
			{"count": 0,"word": "dickfuck"},
			{"count": 0,"word": "dickfucker"},
			{"count": 0,"word": "dickhead"},
			{"count": 0,"word": "dickjuice"},
			{"count": 0,"word": "dickmilk"},
			{"count": 0,"word": "dicksucker"},
			{"count": 0,"word": "dickwad"},
			{"count": 0,"word": "dickweasel"},
			{"count": 0,"word": "dickweed"},
			{"count": 0,"word": "dickwod"},
			{"count": 0,"word": "dipshit"},
			{"count": 0,"word": "doochbag"},
			{"count": 0,"word": "douchefag"},
			{"count": 0,"word": "dumass"},
			{"count": 0,"word": "dumb ass"},
			{"count": 0,"word": "dumbass"},
			{"count": 0,"word": "dumbfuck"},
			{"count": 0,"word": "dumbshit"},
			{"count": 0,"word": "dumshit"},
			{"count": 0,"word": "dick"},
			{"count": 0,"word": "fagfucker"},
			{"count": 0,"word": "fuckers"},
			{"count": 0,"word": "fucken"},
			{"count": 0,"word": "fucking"},
			{"count": 0,"word": "fuckass"},
			{"count": 0,"word": "handjob"},
			{"count": 0,"word": "holyshit"},
			{"count": 0,"word": "motherfucker"},
			{"count": 0,"word": "orgy"},
			{"count": 0,"word": "piss"},
			{"count": 0,"word": "pissed"},
			{"count": 0,"word": "pissing"},
			{"count": 0,"word": "shite"},
			{"count": 0,"word": "whore"}
		],
		substituteWords: [
			{"substitute": "[butt]","word": "anal"},
			{"substitute": "[butt-hat]","word": "ass-hat"},
			{"substitute": "[buttbag]","word": "assbag"},
			{"substitute": "[buttbite]","word": "assbite"},
			{"substitute": "[buttcrook]","word": "asscock"},
			{"substitute": "[butts]","word": "asses"},
			{"substitute": "[buttmate]","word": "assfuck"},
			{"substitute": "[butthead]","word": "asshead"},
			{"substitute": "[butthole]","word": "asshole"},
			{"substitute": "[buttlick]","word": "asslick"},
			{"substitute": "[buttlicker]","word": "asslicker"},
			{"substitute": "[buttmonkey]","word": "assmonkey"},
			{"substitute": "[butmunch]","word": "assmunch"},
			{"substitute": "[buttard]","word": "assshit"},
			{"substitute": "[buttsipper]","word": "asssucker"},
			{"substitute": "[bam]","word": "bampot"},
			{"substitute": "[no father]","word": "bastard"},
			{"substitute": "[dog]","word": "bitch"},
			{"substitute": "[mean]","word": "bitchass"},
			{"substitute": "[mean]","word": "bitchy"},
			{"substitute": "[job]","word": "blowjob"},
			{"substitute": "[crap]","word": "bullshit"},
			{"substitute": "[face]","word": "clitface"},
			{"substitute": "[mess]","word": "clusterfuck"},
			{"substitute": "[rooster]","word": "cock"},
			{"substitute": "[nonsense]","word": "cockass"},
			{"substitute": "[rooster]","word": "cockbite"},
			{"substitute": "[donkey]","word": "cockburger"},
			{"substitute": "[cock]","word": "cockface"},
			{"substitute": "[vex]","word": "cockhead"},
			{"substitute": "[monkey]","word": "cockmonkey"},
			{"substitute": "[nose]","word": "cocknose"},
			{"substitute": "[nugget]","word": "cocknugget"},
			{"substitute": "[cock]","word": "cockshit"},
			{"substitute": "[waffle]","word": "cockwaffle"},
			{"substitute": "[food]","word": "creampie"},
			{"substitute": "[rum]","word": "cum"},
			{"substitute": "[bubble]","word": "cumbubble"},
			{"substitute": "[choosy]","word": "cumdumpster"},
			{"substitute": "[tart]","word": "cumslut"},
			{"substitute": "[tart]","word": "cumtart"},
			{"substitute": "[insult]","word": "cunt"},
			{"substitute": "[irritating]","word": "cuntass"},
			{"substitute": "[bunny]","word": "cuntface"},
			{"substitute": "[napkin]","word": "cuntrag"},
			{"substitute": "[annoying]","word": "cuntslut"},
			{"substitute": "[duck]","word": "damn"},
			{"substitute": "[throat]","word": "deepthroat"},
			{"substitute": "[bob]","word": "dick"},
			{"substitute": "[bag]","word": "dickbag"},
			{"substitute": "[face]","word": "dickface"},
			{"substitute": "[insult]","word": "dickfuck"},
			{"substitute": "[anger]","word": "dickfucker"},
			{"substitute": "[head]","word": "dickhead"},
			{"substitute": "[juice]","word": "dickjuice"},
			{"substitute": "[milk]","word": "dickmilk"},
			{"substitute": "[gay]","word": "dicksucker"},
			{"substitute": "[mean]","word": "dickwad"},
			{"substitute": "[rude]","word": "dickweasel"},
			{"substitute": "[weed]","word": "dickweed"},
			{"substitute": "[annoying]","word": "dickwod"},
			{"substitute": "[toy]","word": "dildo"},
			{"substitute": "[toys]","word": "dildos"},
			{"substitute": "[loser]","word": "dipshit"},
			{"substitute": "[rude]","word": "doochbag"},
			{"substitute": "[duck]","word": "douche"},
			{"substitute": "[throat]","word": "douchebag"},
			{"substitute": "[frat]","word": "douchefag"},
			{"substitute": "[loser]","word": "dumass"},
			{"substitute": "[ass]","word": "dumb ass"},
			{"substitute": "[ass]","word": "dumbass"},
			{"substitute": "[bob]","word": "dumbfuck"},
			{"substitute": "[bob]","word": "dumbshit"},
			{"substitute": "[bob]","word": "dumshit"},
			{"substitute": "[duck]","word": "expression"},
			{"substitute": "[fag]","word": "fagfucker"},
			{"substitute": "[love]","word": "fuck"},
			{"substitute": "[loveable]","word": "fuckable"},
			{"substitute": "[loveass]","word": "fuckass"},
			{"substitute": "[loved]","word": "fucked"},
			{"substitute": "[loven]","word": "fucken"},
			{"substitute": "[lover]","word": "fucker"},
			{"substitute": "[lovers]","word": "fuckers"},
			{"substitute": "[lovin]","word": "fuckin"},
			{"substitute": "[loving]","word": "fucking"},
			{"substitute": "[loves]","word": "fucks"},
			{"substitute": "[lve]","word": "fvck"},
			{"substitute": "[hand]","word": "handjob"},
			{"substitute": "[holy]","word": "holyshit"},
			{"substitute": "[mother]","word": "motherfucker"},
			{"substitute": "[group]","word": "orgy"},
			{"substitute": "[urine]","word": "piss"},
			{"substitute": "[mad]","word": "pissed"},
			{"substitute": "[urinating]","word": "pissing"},
			{"substitute": "[turd]","word": "shit"},
			{"substitute": "[crap]","word": "shite"},
			{"substitute": "[pathetic]","word": "whore"}
		]
	}

    if(details.reason == "install"){
       chrome.storage.sync.set(defaultSettings, function() {
      	console.log("Extension successfully installed");
    });
    }
});

chrome.runtime.onInstalled.addListener(function() {
	
    
  });